# Generated by Django 4.1.7 on 2023-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0003_alter_order_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'waiting'), ('IR', 'in_production'), ('R', 'ready'), ('D', 'done')], default='W', max_length=2),
        ),
    ]
