# Generated by Django 4.1.7 on 2023-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('in_production', 'in_production'), ('ready', 'ready'), ('done', 'done')], default='waiting', max_length=15),
        ),
    ]
