# Generated by Django 4.1.7 on 2023-03-22 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapi', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNAService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('dna_scoring', 'dna_scoring')], default='dna_scoring', max_length=15)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('in_production', 'in_production'), ('ready', 'ready'), ('done', 'done')], default='waiting', max_length=15)),
                ('service_description', models.CharField(blank=True, max_length=200000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
